-- Add multiple-choice and role-based simulation columns to challenges table
ALTER TABLE public.challenges 
ADD COLUMN IF NOT EXISTS response_type text DEFAULT 'freeform' CHECK (response_type IN ('freeform', 'multiple_choice', 'hybrid')),
ADD COLUMN IF NOT EXISTS response_options jsonb DEFAULT NULL,
ADD COLUMN IF NOT EXISTS role_type text DEFAULT NULL CHECK (role_type IN ('CEO', 'CMO', 'CFO', 'CTO', 'COO')),
ADD COLUMN IF NOT EXISTS role_metadata jsonb DEFAULT NULL;

-- Insert sample junior multiple-choice challenges
INSERT INTO public.challenges (title, scenario, question, category, age_range, difficulty_level, response_type, response_options, skills_developed, success_criteria, xp_reward, estimated_minutes, is_active, is_daily_eligible)
VALUES 
('The Snack Stand Dilemma', 
'You started a snack stand at school. Today, your friend wants free snacks, but you need the money to buy more supplies.',
'What do you do?',
'decision', 'junior', 'easy', 'multiple_choice',
'{"options": [{"id": "A", "text": "Give your friend free snacks because friendship is important", "reasoning_prompt": "How will you get money for more supplies?"}, {"id": "B", "text": "Say no - business is business, even with friends", "reasoning_prompt": "How do you explain this to your friend?"}, {"id": "C", "text": "Offer a small discount as a friend deal", "reasoning_prompt": "What discount would be fair?"}, {"id": "D", "text": "Trade - they help you for 10 minutes, they get a free snack", "reasoning_prompt": "What could they help you with?"}]}'::jsonb,
'["critical-thinking", "ethics", "negotiation"]'::jsonb,
'["Shows understanding of business needs", "Considers friendship value", "Finds creative solutions"]'::jsonb,
20, 3, true, true),

('App Idea Clash',
'You and your teammate both have different ideas for your app. You want a game, they want a homework helper. You only have time for one.',
'How do you decide?',
'decision', 'junior', 'easy', 'multiple_choice',
'{"options": [{"id": "A", "text": "Flip a coin to be fair", "reasoning_prompt": "Is random choice the best way?"}, {"id": "B", "text": "Ask other kids which idea they like better", "reasoning_prompt": "Who would you ask?"}, {"id": "C", "text": "Combine both - a game that helps with homework", "reasoning_prompt": "How could that work?"}, {"id": "D", "text": "Take turns - their idea first, yours next time", "reasoning_prompt": "How do you make sure you get your turn?"}]}'::jsonb,
'["teamwork", "decision-making", "creativity"]'::jsonb,
'["Shows respect for teammate", "Uses data/feedback", "Thinks creatively"]'::jsonb,
20, 3, true, true),

('The Broken Promise',
'You promised to deliver 10 friendship bracelets by Friday. It is Thursday and you only have 6 done. Your customer is counting on you!',
'What do you do?',
'scenario', 'junior', 'easy', 'multiple_choice',
'{"options": [{"id": "A", "text": "Stay up late to finish all 10", "reasoning_prompt": "Will they be good quality?"}, {"id": "B", "text": "Tell the customer early and offer 6 now, 4 on Monday", "reasoning_prompt": "How would you explain this?"}, {"id": "C", "text": "Ask a friend to help you make the last 4", "reasoning_prompt": "What would you give them in return?"}, {"id": "D", "text": "Deliver 6 and give a small refund for the delay", "reasoning_prompt": "How much refund is fair?"}]}'::jsonb,
'["accountability", "communication", "problem-solving"]'::jsonb,
'["Takes responsibility", "Communicates proactively", "Offers solutions"]'::jsonb,
20, 3, true, true);

-- Insert role-based challenges
INSERT INTO public.challenges (title, scenario, question, category, age_range, difficulty_level, role_type, role_metadata, skills_developed, success_criteria, xp_reward, estimated_minutes, is_active, is_daily_eligible)
VALUES 
('The Vision Crossroads',
'Two investors want to fund your startup. Investor A offers $50K but wants you to focus only on schools. Investor B offers $30K but lets you keep your original vision of helping everyone.',
'Which investor do you choose and why?',
'decision', 'teen', 'medium', 'CEO',
'{"role_title": "Chief Executive Officer", "role_description": "You see the big picture and make the tough calls that shape the company''s future", "role_emoji": "👔", "typical_decisions": ["Company vision", "Major partnerships", "Funding decisions", "Culture setting"]}'::jsonb,
'["strategic-thinking", "vision", "decision-making"]'::jsonb,
'["Weighs long-term vs short-term", "Considers mission alignment", "Articulates clear reasoning"]'::jsonb,
30, 5, true, true),

('The Co-founder Conflict',
'Your co-founder and best friend wants to pivot the company in a completely different direction. The team is split 50/50. As CEO, you have the deciding vote.',
'How do you handle this situation?',
'scenario', 'teen', 'hard', 'CEO',
'{"role_title": "Chief Executive Officer", "role_description": "You see the big picture and make the tough calls that shape the company''s future", "role_emoji": "👔", "typical_decisions": ["Company vision", "Major partnerships", "Funding decisions", "Culture setting"]}'::jsonb,
'["leadership", "conflict-resolution", "communication"]'::jsonb,
'["Respects co-founder relationship", "Gathers team input", "Makes decisive choice with reasoning"]'::jsonb,
30, 5, true, true),

('The Viral Moment',
'A famous TikToker with 2 million followers just used your product and loved it! They want to post about it but are asking for $5,000. Your marketing budget is only $3,000.',
'What is your marketing play?',
'decision', 'teen', 'medium', 'CMO',
'{"role_title": "Chief Marketing Officer", "role_description": "You make people fall in love with the product and drive growth", "role_emoji": "📣", "typical_decisions": ["Brand messaging", "Marketing campaigns", "Customer acquisition", "Social media strategy"]}'::jsonb,
'["negotiation", "marketing", "creativity"]'::jsonb,
'["Maximizes opportunity", "Stays within constraints", "Thinks creatively about value exchange"]'::jsonb,
30, 5, true, true),

('The Negative Review Storm',
'Your app just got 50 one-star reviews overnight because of a bug that has now been fixed. Your rating dropped from 4.8 to 3.9. The App Store is your main customer source.',
'How do you recover your reputation?',
'scenario', 'teen', 'hard', 'CMO',
'{"role_title": "Chief Marketing Officer", "role_description": "You make people fall in love with the product and drive growth", "role_emoji": "📣", "typical_decisions": ["Brand messaging", "Marketing campaigns", "Customer acquisition", "Social media strategy"]}'::jsonb,
'["crisis-management", "communication", "customer-relations"]'::jsonb,
'["Responds quickly", "Shows accountability", "Has recovery plan"]'::jsonb,
30, 5, true, true),

('The Runway Crisis',
'Your startup has $15,000 in the bank. Monthly costs are $5,000. That is 3 months of runway. Revenue is growing but slowly - you made $1,000 last month.',
'How do you extend your runway while still growing?',
'thought', 'teen', 'hard', 'CFO',
'{"role_title": "Chief Financial Officer", "role_description": "Every dollar counts, and you know exactly where they all go", "role_emoji": "💰", "typical_decisions": ["Budget allocation", "Financial forecasting", "Cost optimization", "Funding strategy"]}'::jsonb,
'["financial-planning", "prioritization", "strategic-thinking"]'::jsonb,
'["Shows financial awareness", "Identifies cost cuts", "Balances growth vs survival"]'::jsonb,
30, 5, true, true),

('The Pricing Puzzle',
'Your product costs $10/month. Customers love it but many say it is too expensive. Your competitor charges $5 but has fewer features. Your costs are $3 per user.',
'What is your pricing strategy?',
'decision', 'teen', 'medium', 'CFO',
'{"role_title": "Chief Financial Officer", "role_description": "Every dollar counts, and you know exactly where they all go", "role_emoji": "💰", "typical_decisions": ["Budget allocation", "Financial forecasting", "Cost optimization", "Funding strategy"]}'::jsonb,
'["pricing-strategy", "market-analysis", "value-communication"]'::jsonb,
'["Understands unit economics", "Considers customer segments", "Articulates value proposition"]'::jsonb,
30, 5, true, true),

('The Launch Day Bug',
'Your app launches tomorrow to 10,000 waiting users. Tonight, you discovered a bug that crashes the app for 20% of users. Fixing it properly takes 3 days. A quick fix takes 4 hours but might cause other issues.',
'What is your technical decision?',
'decision', 'teen', 'hard', 'CTO',
'{"role_title": "Chief Technology Officer", "role_description": "You decide what gets built, how it gets built, and when it ships", "role_emoji": "💻", "typical_decisions": ["Technical architecture", "Build vs buy", "Launch decisions", "Team priorities"]}'::jsonb,
'["risk-assessment", "decision-making", "technical-judgment"]'::jsonb,
'["Weighs risks clearly", "Considers user impact", "Has communication plan"]'::jsonb,
30, 5, true, true),

('The AI vs Human Choice',
'You can build a feature two ways: Using AI that is 80% accurate but instant, or hiring humans that are 99% accurate but slow and expensive. Users want speed, but mistakes could hurt your reputation.',
'Which approach do you choose?',
'thought', 'teen', 'medium', 'CTO',
'{"role_title": "Chief Technology Officer", "role_description": "You decide what gets built, how it gets built, and when it ships", "role_emoji": "💻", "typical_decisions": ["Technical architecture", "Build vs buy", "Launch decisions", "Team priorities"]}'::jsonb,
'["technical-strategy", "trade-off-analysis", "innovation"]'::jsonb,
'["Understands trade-offs", "Considers hybrid approaches", "Thinks about iteration"]'::jsonb,
30, 5, true, true),

('The Supplier Shock',
'Your main supplier just doubled their prices. You have orders to fulfill this week. Finding a new supplier takes 2 weeks. Raising your prices might lose customers.',
'How do you keep operations running?',
'scenario', 'teen', 'hard', 'COO',
'{"role_title": "Chief Operating Officer", "role_description": "You keep everything running smoothly - from suppliers to delivery", "role_emoji": "⚙️", "typical_decisions": ["Supply chain", "Process optimization", "Vendor management", "Quality control"]}'::jsonb,
'["operations", "crisis-management", "negotiation"]'::jsonb,
'["Acts quickly", "Explores multiple options", "Maintains customer trust"]'::jsonb,
30, 5, true, true),

('The Scale Challenge',
'Your handmade product business is booming! You are getting 100 orders/week but can only make 30. Hiring help means lower quality. Using a factory means less personal touch.',
'How do you scale without losing what makes you special?',
'thought', 'teen', 'medium', 'COO',
'{"role_title": "Chief Operating Officer", "role_description": "You keep everything running smoothly - from suppliers to delivery", "role_emoji": "⚙️", "typical_decisions": ["Supply chain", "Process optimization", "Vendor management", "Quality control"]}'::jsonb,
'["scaling", "quality-management", "strategic-thinking"]'::jsonb,
'["Considers quality trade-offs", "Thinks about brand identity", "Has phased approach"]'::jsonb,
30, 5, true, true);