-- Seed 120 challenges across 4 industry tracks (30 each)
-- Sustainability, Fashion, Aviation, Gaming

-- First, get track IDs
DO $$
DECLARE
  sustainability_id uuid;
  fashion_id uuid;
  aviation_id uuid;
  gaming_id uuid;
BEGIN
  SELECT id INTO sustainability_id FROM industry_tracks WHERE slug = 'sustainability';
  SELECT id INTO fashion_id FROM industry_tracks WHERE slug = 'fashion-retail';
  SELECT id INTO aviation_id FROM industry_tracks WHERE slug = 'aviation-events';
  SELECT id INTO gaming_id FROM industry_tracks WHERE slug = 'gaming-entertainment';

  -- ============ SUSTAINABILITY TRACK (30 challenges) ============
  
  -- DISCOVER pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('The Plastic Problem', 'Only 9% of all plastic ever made has been recycled. The rest ends up in landfills, oceans, or burned. A city wants to dramatically increase recycling rates.', 'What''s the real problem here - is it the people, the system, or the materials?', 'thought', 'discover', sustainability_id, 'medium', 4, 30, '["Problem Analysis", "Systems Thinking", "Research"]', '["Identifies root cause", "Shows systems understanding", "Proposes research direction"]', '{"fun_facts": ["A plastic bottle takes 450 years to decompose", "The Great Pacific Garbage Patch is twice the size of Texas", "Every minute, 1 million plastic bottles are bought globally"], "career_connections": ["Environmental Scientist", "Sustainability Consultant", "Waste Management Engineer"], "company_examples": ["TerraCycle", "Loop Industries", "Plastic Bank"]}', 'teen'),
  
  ('Why No Solar?', 'Dubai has 350+ sunny days per year, yet most homes don''t have solar panels. A startup wants to change this but needs to understand why adoption is low.', 'What are the top 3 barriers preventing families from installing solar panels?', 'decision', 'discover', sustainability_id, 'medium', 3, 25, '["Market Research", "Customer Discovery", "Problem Analysis"]', '["Lists 3 specific barriers", "Shows customer empathy", "Identifies solvable problems"]', '{"fun_facts": ["Dubai''s Mohammed bin Rashid Solar Park will be the largest in the world", "Solar panel costs dropped 99% since 1976", "UAE aims for 50% clean energy by 2050"], "career_connections": ["Solar Energy Engineer", "Clean Tech Sales", "Energy Policy Analyst"], "company_examples": ["Masdar", "Yellow Door Energy", "DEWA"]}', 'teen'),
  
  ('The Food Waste Mystery', 'Hotels throw away 30% of the food they prepare. A tech startup wants to reduce this waste but needs to understand the root causes first.', 'What questions would you ask hotel managers to discover the real reasons for food waste?', 'thought', 'discover', sustainability_id, 'easy', 3, 25, '["Interview Skills", "Problem Discovery", "Hypothesis Formation"]', '["Asks open-ended questions", "Targets root causes", "Shows curiosity"]', '{"fun_facts": ["1/3 of all food produced globally is wasted", "Food waste generates 8% of greenhouse gases", "A hotel buffet wastes an average of 20kg per day"], "career_connections": ["Food Systems Analyst", "Hospitality Consultant", "Supply Chain Manager"], "company_examples": ["Too Good To Go", "Winnow", "FoodCloud"]}', 'teen'),
  
  ('The Water Footprint', 'It takes 2,700 liters of water to make one cotton t-shirt. A fashion startup wants to create sustainable clothing but realizes few people know about this.', 'Is the problem consumer awareness, production methods, or something else entirely?', 'thought', 'discover', sustainability_id, 'hard', 4, 35, '["Critical Thinking", "Research", "Problem Framing"]', '["Analyzes multiple angles", "Identifies key stakeholders", "Proposes discovery approach"]', '{"fun_facts": ["Making one pair of jeans uses 7,500 liters of water", "Fashion industry is the second largest water polluter", "Only 1% of used clothing is recycled into new garments"], "career_connections": ["Sustainable Fashion Designer", "Environmental Auditor", "Supply Chain Analyst"], "company_examples": ["Patagonia", "Reformation", "Eileen Fisher"]}', 'teen'),
  
  ('Electric Vehicle Hesitation', 'Despite government incentives, many families still prefer gas cars over electric. You''re researching why EV adoption isn''t faster.', 'What''s the biggest fear or misconception holding people back from buying EVs?', 'decision', 'discover', sustainability_id, 'medium', 3, 25, '["Customer Research", "Empathy", "Market Analysis"]', '["Identifies emotional barriers", "Shows research approach", "Distinguishes facts from fears"]', '{"fun_facts": ["Norway has 80% EV market share", "EVs have 90% fewer moving parts than gas cars", "UAE has over 300 free charging stations"], "career_connections": ["EV Product Manager", "Automotive Engineer", "Clean Energy Advocate"], "company_examples": ["Tesla", "Rivian", "BYD"]}', 'teen'),
  
  ('The Air Quality Question', 'Indoor air pollution is 2-5x worse than outdoor. Most people spend 90% of their time indoors but don''t know about this health risk.', 'How would you research what people currently believe about indoor air quality?', 'thought', 'discover', sustainability_id, 'medium', 4, 30, '["Research Design", "Hypothesis Testing", "Health Tech"]', '["Proposes research method", "Identifies assumptions to test", "Shows scientific thinking"]', '{"fun_facts": ["Plants can remove up to 87% of air toxins in 24 hours", "Cooking releases fine particles smaller than 2.5 microns", "Indoor air has 100+ chemical compounds"], "career_connections": ["Environmental Health Scientist", "Air Quality Engineer", "Public Health Researcher"], "company_examples": ["Dyson", "IQAir", "Airthings"]}', 'teen'),
  
  ('Carbon Footprint Blindspot', 'The average person has no idea what activities contribute most to their carbon footprint. Many think they''re helping the environment but aren''t.', 'What activities do you think people BELIEVE are helping but actually don''t make much difference?', 'scenario', 'discover', sustainability_id, 'hard', 4, 30, '["Critical Analysis", "Research", "Myth Busting"]', '["Identifies common misconceptions", "Uses evidence", "Shows analytical thinking"]', '{"fun_facts": ["Flights account for 12% of transport emissions but just 2% of global emissions", "Turning off lights saves far less CO2 than eating less meat", "One round-trip flight = 1 year of recycling"], "career_connections": ["Carbon Analyst", "Climate Scientist", "Sustainability Educator"], "company_examples": ["Wren", "Joro", "Klima"]}', 'teen'),
  
  ('The Renewable Energy Gap', 'Schools have large rooftops and use electricity during sunny hours - perfect for solar. Yet most schools don''t have panels. You''re investigating why.', 'What are the top 3 questions you would ask a school principal about solar adoption?', 'decision', 'discover', sustainability_id, 'easy', 3, 25, '["Stakeholder Interviews", "Problem Discovery", "Education Sector"]', '["Asks specific questions", "Considers decision-makers", "Identifies barriers"]', '{"fun_facts": ["A school rooftop solar system can save $50,000/year", "Solar panels last 25-30 years", "Schools can sell excess power back to the grid"], "career_connections": ["Renewable Energy Consultant", "School Administrator", "Energy Broker"], "company_examples": ["SunPower", "Solar4Schools", "Engie"]}', 'teen');

  -- DESIGN pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('The Smart Recycling Bin', 'Current recycling bins have a 40% contamination rate - people put wrong items in wrong bins. You need to design a solution that helps people recycle correctly.', 'Design a smart bin system that helps people recycle correctly. What features would it have?', 'thought', 'design', sustainability_id, 'medium', 5, 35, '["Product Design", "User Experience", "Behavior Change"]', '["Proposes specific features", "Considers user behavior", "Solves contamination problem"]', '{"fun_facts": ["Contaminated recycling often goes to landfill anyway", "AI can identify recyclables with 95% accuracy", "Singapore uses underground pneumatic waste collection"], "career_connections": ["Product Designer", "UX Researcher", "Waste Tech Entrepreneur"], "company_examples": ["Oscar", "Bin-e", "CleanRobotics"]}', 'teen'),
  
  ('Carbon Tracker App', 'People want to reduce their carbon footprint but don''t know where to start. Design an app that makes tracking and reducing carbon easy and fun.', 'What 3 core features would your carbon tracking app have to make it actually useful?', 'decision', 'design', sustainability_id, 'medium', 4, 30, '["App Design", "Gamification", "Behavior Change"]', '["Lists 3 specific features", "Makes it engaging", "Provides actionable insights"]', '{"fun_facts": ["The average person produces 4 tons of CO2 per year", "Small changes can reduce footprint by 20%", "Gamification increases app engagement by 40%"], "career_connections": ["App Developer", "Climate Tech PM", "Behavioral Scientist"], "company_examples": ["Joro", "Capture", "Earth Hero"]}', 'teen'),
  
  ('Solar Panel Subscription', 'Many families can''t afford $15,000 upfront for solar panels. Design a subscription service that makes solar accessible to everyone.', 'How would your solar subscription work? Describe the pricing and key benefits.', 'scenario', 'design', sustainability_id, 'hard', 5, 35, '["Business Model Design", "Pricing Strategy", "Accessibility"]', '["Creates viable pricing model", "Addresses affordability", "Shows clear value proposition"]', '{"fun_facts": ["Solar subscriptions have grown 300% in 5 years", "Leasing can eliminate upfront costs", "Some plans pay homeowners for excess energy"], "career_connections": ["Business Development", "Fintech Product Manager", "Clean Energy Sales"], "company_examples": ["Sunrun", "Sunnova", "Palmetto"]}', 'teen'),
  
  ('The Food Rescue Network', 'Restaurants throw away perfectly good food every night while homeless shelters need meals. Design a system to connect them efficiently.', 'Design the workflow: How does food get from restaurant to shelter in your system?', 'thought', 'design', sustainability_id, 'medium', 5, 35, '["System Design", "Logistics", "Social Impact"]', '["Creates clear workflow", "Addresses logistics", "Ensures food safety"]', '{"fun_facts": ["40% of restaurant food is thrown away", "Rescued food can feed millions", "Apps have saved 150M+ meals from waste"], "career_connections": ["Logistics Coordinator", "Social Enterprise Founder", "Supply Chain Manager"], "company_examples": ["Too Good To Go", "Feeding America", "FoodCloud"]}', 'teen'),
  
  ('Eco Score Labels', 'Shoppers want to buy sustainable products but don''t know which ones are actually eco-friendly. Design a simple labeling system for products.', 'Create a simple eco-score system: What would you measure and how would you display it?', 'decision', 'design', sustainability_id, 'medium', 4, 30, '["Information Design", "User Experience", "Sustainability Metrics"]', '["Creates clear scoring system", "Chooses right metrics", "Designs simple display"]', '{"fun_facts": ["73% of consumers want to buy sustainable products", "Most eco-labels are confusing or misleading", "France requires eco-scores on all food products"], "career_connections": ["Sustainability Analyst", "Product Manager", "Information Designer"], "company_examples": ["EcoScore", "Good On You", "EWG"]}', 'teen'),
  
  ('The Green Commute', 'A company wants to reduce employee commuting emissions by 50%. Currently most employees drive alone. Design an incentive program.', 'What incentives would actually get people to change their commute habits?', 'scenario', 'design', sustainability_id, 'medium', 4, 30, '["Behavior Change", "Incentive Design", "Transportation"]', '["Proposes specific incentives", "Addresses real barriers", "Creates measurable program"]', '{"fun_facts": ["Average commute produces 3 tons CO2/year", "Remote work reduces emissions by 54%", "Bike commuters are happier and healthier"], "career_connections": ["HR Sustainability Lead", "Transportation Planner", "Corporate Social Responsibility"], "company_examples": ["Luum", "RideAmigos", "Strava Metro"]}', 'teen'),
  
  ('Water-Saving Shower', 'A 10-minute shower uses 80 liters of water. Design a product or system that helps people reduce shower water usage without sacrificing experience.', 'Describe your water-saving shower solution. How does it work and what makes it appealing?', 'thought', 'design', sustainability_id, 'hard', 5, 35, '["Product Innovation", "User Experience", "Resource Conservation"]', '["Creates innovative solution", "Maintains user experience", "Shows water savings"]', '{"fun_facts": ["Showers account for 17% of indoor water use", "Low-flow showerheads save 7,500 liters/year", "Some smart showers recycle water in real-time"], "career_connections": ["Product Engineer", "Industrial Designer", "Water Conservation Specialist"], "company_examples": ["Orbital Systems", "Nebia", "Hydrao"]}', 'teen'),
  
  ('Packaging-Free Delivery', 'E-commerce creates tons of packaging waste. Design a reusable packaging system for online shopping.', 'How would your reusable packaging system work? Describe the full loop from delivery to return.', 'thought', 'design', sustainability_id, 'hard', 5, 35, '["Circular Economy", "Logistics Design", "Sustainability"]', '["Creates complete loop", "Addresses return logistics", "Makes it convenient"]', '{"fun_facts": ["165 billion packages shipped in US yearly", "Packaging is 30% of landfill waste", "Reusable packaging can be used 50+ times"], "career_connections": ["Packaging Engineer", "Logistics Designer", "Sustainability Director"], "company_examples": ["Loop", "RePack", "LimeLoop"]}', 'teen');

  -- BUILD pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('School Energy Audit', 'Your school wastes energy through old equipment, lights left on, and inefficient heating. You''ve been asked to create a 30-day energy reduction plan.', 'Create a week-by-week action plan to reduce your school''s energy usage by 20%.', 'scenario', 'build', sustainability_id, 'medium', 5, 35, '["Project Planning", "Resource Management", "Implementation"]', '["Creates specific timeline", "Lists actionable steps", "Sets measurable goals"]', '{"fun_facts": ["Schools can reduce energy costs by 25% with no-cost changes", "LED lighting uses 75% less energy", "Smart thermostats save 10-15% on heating"], "career_connections": ["Energy Auditor", "Facilities Manager", "Sustainability Coordinator"], "company_examples": ["Engie", "Schneider Electric", "JCI"]}', 'teen'),
  
  ('Community Garden Launch', 'You want to start a community garden in an unused lot in your neighborhood. You have $500 budget and need to launch in 3 months.', 'Break down your garden project into phases with specific tasks and timeline.', 'thought', 'build', sustainability_id, 'medium', 5, 35, '["Project Management", "Community Building", "Resource Allocation"]', '["Creates phased plan", "Allocates budget", "Includes community engagement"]', '{"fun_facts": ["Community gardens increase property values by 9%", "Urban gardens can produce 20x more food per acre", "Gardening reduces stress and improves mental health"], "career_connections": ["Urban Farmer", "Community Organizer", "Landscape Designer"], "company_examples": ["Growing Communities", "Urban Harvest", "Gotham Greens"]}', 'teen'),
  
  ('Plastic-Free Challenge', 'You''re launching a "plastic-free week" challenge at your school. Create a practical guide students can actually follow.', 'List 10 specific swaps students can make for plastic-free living during the challenge week.', 'decision', 'build', sustainability_id, 'easy', 4, 25, '["Practical Planning", "Behavior Change", "Communication"]', '["Lists 10 specific swaps", "Makes them achievable", "Includes alternatives"]', '{"fun_facts": ["Average person uses 150 plastic bags yearly", "Plastic-free alternatives often save money", "Small changes create lasting habits"], "career_connections": ["Sustainability Educator", "Campaign Manager", "Zero Waste Consultant"], "company_examples": ["Package Free Shop", "Zero Waste Store", "EcoVibe"]}', 'teen'),
  
  ('Solar Pitch Deck', 'You''re pitching a solar panel installation to your school board. Create the key slides for your presentation.', 'What 5 slides would you include in your solar pitch, and what''s the key message of each?', 'scenario', 'build', sustainability_id, 'hard', 5, 35, '["Presentation Skills", "Persuasion", "Business Case"]', '["Creates 5 compelling slides", "Includes data/ROI", "Has clear call to action"]', '{"fun_facts": ["Solar panels add $15,000 to home value", "School solar systems pay back in 5-7 years", "Visual presentations are 43% more persuasive"], "career_connections": ["Sales Engineer", "Business Development", "Renewable Energy Consultant"], "company_examples": ["SunPower", "Tesla Solar", "Enphase"]}', 'teen'),
  
  ('E-Waste Collection', 'Your school has old electronics piling up. Create a plan for an e-waste collection and recycling program.', 'Design your e-waste collection program: How will you collect, sort, and recycle responsibly?', 'thought', 'build', sustainability_id, 'medium', 5, 35, '["Program Design", "Logistics", "Environmental Responsibility"]', '["Creates collection process", "Ensures responsible recycling", "Includes education component"]', '{"fun_facts": ["Only 17% of e-waste is properly recycled", "E-waste contains valuable gold, silver, and rare metals", "One ton of phones contains 300g of gold"], "career_connections": ["E-Waste Recycling Specialist", "Environmental Program Manager", "Circular Economy Consultant"], "company_examples": ["Call2Recycle", "ERI", "Sims Recycling"]}', 'teen'),
  
  ('Green Team Formation', 'You''re starting an environmental club at school. Create a plan to recruit members and make real impact in the first semester.', 'Create a semester plan for your green team: recruitment strategy, first 3 projects, and how you''ll measure success.', 'thought', 'build', sustainability_id, 'medium', 5, 30, '["Leadership", "Team Building", "Project Planning"]', '["Includes recruitment plan", "Proposes 3 projects", "Defines success metrics"]', '{"fun_facts": ["Student-led initiatives are 60% more effective", "Environmental clubs improve school recycling by 30%", "Team projects build lifelong skills"], "career_connections": ["Environmental Advocate", "Community Organizer", "Nonprofit Director"], "company_examples": ["350.org", "Fridays for Future", "One Tree Planted"]}', 'teen'),
  
  ('Composting System', 'Your school cafeteria throws away 50kg of food waste daily. Design and plan a composting system to turn this waste into garden soil.', 'Create a step-by-step plan to implement composting at your school cafeteria.', 'scenario', 'build', sustainability_id, 'medium', 5, 35, '["System Implementation", "Process Design", "Waste Management"]', '["Creates implementation steps", "Addresses logistics", "Plans for maintenance"]', '{"fun_facts": ["Composting reduces waste by 30%", "Compost is worth $20-40 per ton", "Food scraps decompose in 2-4 weeks"], "career_connections": ["Waste Management Specialist", "Urban Agriculture Manager", "Sustainability Coordinator"], "company_examples": ["CompostNow", "BioEnergy", "Harvest Power"]}', 'teen');

  -- EXPLORE pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Why Masdar City?', 'The UAE built Masdar City - a planned sustainable city powered entirely by renewable energy. It''s one of the most ambitious sustainability projects ever.', 'Why did the UAE invest billions in a sustainable city? What can other countries learn from it?', 'thought', 'explore', sustainability_id, 'medium', 4, 30, '["Global Thinking", "Policy Analysis", "Future Planning"]', '["Explains strategic reasoning", "Identifies lessons learned", "Shows global perspective"]', '{"fun_facts": ["Masdar City is 50% cooler than surrounding desert", "It uses 75% less energy than normal cities", "Zero carbon emissions from transportation"], "career_connections": ["Urban Planner", "Sustainability Consultant", "Climate Policy Analyst"], "company_examples": ["Masdar", "AECOM", "Arup"]}', 'teen'),
  
  ('Carbon Credits Explained', 'Companies buy "carbon credits" to offset their emissions. This is a $2 billion market but controversial. Some say it''s real, others say it''s "greenwashing."', 'Are carbon credits effective at fighting climate change? Explain both sides of the debate.', 'thought', 'explore', sustainability_id, 'hard', 5, 35, '["Critical Analysis", "Economics", "Environmental Science"]', '["Explains both perspectives", "Uses evidence", "Forms reasoned opinion"]', '{"fun_facts": ["One carbon credit = one ton of CO2", "Voluntary carbon market grew 190% in 2021", "Some credits fund tree planting, others renewable energy"], "career_connections": ["Carbon Market Analyst", "ESG Consultant", "Climate Finance Specialist"], "company_examples": ["South Pole", "Pachama", "Verra"]}', 'teen'),
  
  ('The Hydrogen Economy', 'Some experts say hydrogen will replace oil as the world''s main energy source. Others say it''s too expensive and inefficient.', 'What are the pros and cons of hydrogen as a clean energy source?', 'thought', 'explore', sustainability_id, 'hard', 5, 35, '["Energy Literacy", "Critical Evaluation", "Future Thinking"]', '["Lists specific pros", "Lists specific cons", "Shows balanced understanding"]', '{"fun_facts": ["Hydrogen produces only water when burned", "Green hydrogen costs 3-6x more than natural gas", "Dubai opened Middle East''s first green hydrogen plant"], "career_connections": ["Hydrogen Engineer", "Energy Analyst", "Clean Tech Investor"], "company_examples": ["Air Liquide", "Plug Power", "ITM Power"]}', 'teen'),
  
  ('Fast Fashion Impact', 'The fashion industry produces 10% of global carbon emissions - more than international flights and maritime shipping combined.', 'Why is fast fashion so harmful to the environment, and what would a sustainable alternative look like?', 'thought', 'explore', sustainability_id, 'medium', 4, 30, '["Industry Analysis", "Systems Thinking", "Sustainability"]', '["Explains environmental impact", "Identifies root causes", "Proposes alternatives"]', '{"fun_facts": ["Average garment is worn 7 times before disposal", "Textile dyeing is #2 water polluter globally", "Resale market growing 25x faster than retail"], "career_connections": ["Sustainable Fashion Consultant", "Circular Economy Designer", "Fashion Tech Entrepreneur"], "company_examples": ["ThredUp", "Rent the Runway", "For Days"]}', 'teen'),
  
  ('Nuclear Revival', 'After decades of decline, nuclear power is being reconsidered as a clean energy source. Some countries are building new plants while others are shutting them down.', 'Should we build more nuclear power plants to fight climate change? Defend your position.', 'thought', 'explore', sustainability_id, 'hard', 5, 35, '["Energy Policy", "Risk Analysis", "Argumentation"]', '["Takes clear position", "Addresses safety concerns", "Uses evidence"]', '{"fun_facts": ["Nuclear produces 10% of global electricity", "France gets 70% of power from nuclear", "Modern reactors are 100x safer than 1970s designs"], "career_connections": ["Nuclear Engineer", "Energy Policy Analyst", "Climate Researcher"], "company_examples": ["TerraPower", "NuScale", "EDF"]}', 'teen'),
  
  ('Biodiversity Banking', 'Companies are now buying "biodiversity credits" - paying to protect endangered species and ecosystems. Is this the future of conservation?', 'How could putting a price on nature help or hurt conservation efforts?', 'thought', 'explore', sustainability_id, 'hard', 5, 35, '["Economics", "Conservation", "Ethical Reasoning"]', '["Explores both benefits and risks", "Shows understanding of incentives", "Considers ethical implications"]', '{"fun_facts": ["Half of global GDP depends on nature", "Biodiversity credits market could reach $40B", "Species extinction rate is 1000x natural rate"], "career_connections": ["Conservation Finance Specialist", "Ecosystem Services Analyst", "Environmental Economist"], "company_examples": ["Wallacea Trust", "NatureVest", "Conservation International"]}', 'teen'),
  
  ('Right to Repair', 'Many electronics are designed to be impossible to repair, forcing people to buy new ones. The "right to repair" movement wants to change this.', 'Should companies be required to make products repairable? What are the arguments on each side?', 'thought', 'explore', sustainability_id, 'medium', 4, 30, '["Consumer Rights", "Circular Economy", "Policy Analysis"]', '["Presents both sides", "Considers business and consumer perspectives", "Forms reasoned conclusion"]', '{"fun_facts": ["Average smartphone lasts only 2.5 years", "EU passed right-to-repair laws in 2021", "Repair cafes have fixed 1.5M items"], "career_connections": ["Product Sustainability Manager", "Consumer Advocate", "Policy Researcher"], "company_examples": ["iFixit", "Fairphone", "Framework"]}', 'teen');

  -- ============ FASHION & RETAIL TRACK (30 challenges) ============
  
  -- DISCOVER pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('The Returns Problem', 'Online fashion has a 30% return rate - 3x higher than physical stores. Returns cost retailers billions and create massive waste.', 'What''s the root cause of high return rates in online fashion? How would you research this?', 'thought', 'discover', fashion_id, 'medium', 4, 30, '["Problem Analysis", "Customer Research", "E-commerce"]', '["Identifies multiple causes", "Proposes research approach", "Shows customer empathy"]', '{"fun_facts": ["5 billion lbs of returns go to landfills yearly", "Virtual try-on reduces returns by 40%", "Size uncertainty causes 52% of fashion returns"], "career_connections": ["E-commerce Analyst", "UX Researcher", "Retail Tech PM"], "company_examples": ["True Fit", "Fit Analytics", "3DLOOK"]}', 'teen'),
  
  ('Trend Prediction Mystery', 'Fashion brands must predict trends 6-18 months before items hit stores. Get it wrong and you lose millions. Get it right and you dominate.', 'How do fashion companies know what people will want to wear next year?', 'thought', 'discover', fashion_id, 'medium', 4, 30, '["Trend Analysis", "Data Science", "Fashion Business"]', '["Identifies data sources", "Explains prediction methods", "Shows industry understanding"]', '{"fun_facts": ["Zara can go from design to store in 2 weeks", "AI can analyze millions of social media images for trends", "Color trends are predicted 2 years in advance"], "career_connections": ["Trend Forecaster", "Fashion Data Scientist", "Buying Director"], "company_examples": ["WGSN", "Edited", "Heuritech"]}', 'teen'),
  
  ('The Sizing Chaos', 'A size "Medium" is different at every brand. This frustrates shoppers and causes returns. You''re researching why this problem persists.', 'Why don''t all clothing brands use the same sizing system? What''s stopping them?', 'thought', 'discover', fashion_id, 'medium', 4, 30, '["Industry Analysis", "Standardization", "Customer Experience"]', '["Identifies barriers", "Considers stakeholder interests", "Shows systems thinking"]', '{"fun_facts": ["There are over 50 different sizing systems globally", "Size 8 has grown 6 inches since 1958", "Body scanning could eliminate sizing confusion"], "career_connections": ["Fashion Standards Analyst", "Retail Consultant", "Product Development"], "company_examples": ["Bold Metrics", "Presize", "Virtusize"]}', 'teen'),
  
  ('Influencer Fatigue', 'Consumers are growing tired of influencer marketing - they don''t trust sponsored posts. But brands still spend billions on influencers.', 'What''s changing about how young people discover and trust fashion recommendations?', 'thought', 'discover', fashion_id, 'medium', 4, 30, '["Consumer Behavior", "Marketing Research", "Social Media"]', '["Identifies trust factors", "Shows generational understanding", "Proposes alternatives"]', '{"fun_facts": ["Trust in influencers dropped 25% in 3 years", "Micro-influencers have 7x higher engagement", "User-generated content drives 6x more conversions"], "career_connections": ["Social Media Strategist", "Brand Manager", "Consumer Researcher"], "company_examples": ["LTK", "Tagger", "AspireIQ"]}', 'teen'),
  
  ('Rental vs Own', 'Clothing rental is growing fast - especially for special occasions. But many people still prefer to own their clothes outright.', 'What emotional and practical factors determine whether someone rents or buys clothing?', 'thought', 'discover', fashion_id, 'medium', 4, 30, '["Consumer Psychology", "Business Models", "Behavior Research"]', '["Identifies emotional factors", "Lists practical considerations", "Shows customer understanding"]', '{"fun_facts": ["Clothing rental market growing 10% yearly", "Average outfit is worn 7 times", "Gen Z is 2x more likely to rent than Boomers"], "career_connections": ["Consumer Psychologist", "Fashion Business Analyst", "Circular Economy Consultant"], "company_examples": ["Rent the Runway", "Hurr", "By Rotation"]}', 'teen'),
  
  ('The Fit Tech Gap', 'Despite advanced technology, most people still can''t find clothes that fit well online. Virtual fitting rooms exist but aren''t widely used.', 'Why hasn''t technology solved the online fitting problem yet? What''s still missing?', 'thought', 'discover', fashion_id, 'hard', 4, 30, '["Technology Analysis", "User Adoption", "Problem Definition"]', '["Identifies technology gaps", "Considers user barriers", "Proposes what''s needed"]', '{"fun_facts": ["Only 3% of shoppers use virtual try-on", "AR fitting can increase conversion 200%", "Perfect fit requires 140+ body measurements"], "career_connections": ["Fashion Tech Product Manager", "AR/VR Developer", "Retail Innovation Lead"], "company_examples": ["Zeekit", "Vue.ai", "Snap AR"]}', 'teen'),
  
  ('Secondhand Stigma', 'Thrift shopping is trendy among some groups but still carries stigma for others. Resale platforms are trying to make secondhand fashionable.', 'What makes some people embrace thrift shopping while others avoid it?', 'thought', 'discover', fashion_id, 'easy', 3, 25, '["Social Research", "Consumer Behavior", "Brand Perception"]', '["Identifies social factors", "Shows demographic understanding", "Explores motivations"]', '{"fun_facts": ["Secondhand market will double by 2026", "Luxury resale is the fastest-growing segment", "52% of Gen Z bought secondhand last year"], "career_connections": ["Resale Platform PM", "Sustainability Marketer", "Fashion Sociologist"], "company_examples": ["Depop", "ThredUp", "The RealReal"]}', 'teen'),
  
  ('Local Designer Struggle', 'Independent designers create amazing unique pieces but struggle to compete with fast fashion giants. Most close within 3 years.', 'What are the top 3 challenges local fashion designers face in competing with big brands?', 'decision', 'discover', fashion_id, 'medium', 3, 25, '["Industry Analysis", "Small Business", "Competitive Strategy"]', '["Lists 3 specific challenges", "Shows industry understanding", "Considers solutions"]', '{"fun_facts": ["90% of fashion businesses are SMEs", "Big brands can copy designs in weeks", "Direct-to-consumer saves designers 50%+ in margins"], "career_connections": ["Fashion Entrepreneur", "Boutique Buyer", "Designer Brand Consultant"], "company_examples": ["Shopify", "Pietra", "Faire"]}', 'teen');

  -- DESIGN pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('AI Personal Stylist', 'You''re designing an AI stylist app that helps people build a wardrobe that actually works together. Currently, people buy items that don''t match.', 'Design the core features of an AI stylist app. What would make it actually useful?', 'thought', 'design', fashion_id, 'medium', 5, 35, '["App Design", "AI Application", "User Experience"]', '["Proposes 3+ core features", "Solves real problem", "Creates engaging experience"]', '{"fun_facts": ["Average person wears only 20% of their wardrobe", "AI can match outfits 30% better than humans", "Stitch Fix uses 85 data points per customer"], "career_connections": ["AI Product Designer", "Fashion Tech PM", "UX Designer"], "company_examples": ["Stitch Fix", "Cladwell", "Lookiero"]}', 'teen'),
  
  ('Virtual Showroom', 'Fashion brands need to show new collections to buyers but flying them in is expensive and wasteful. Design a virtual showroom experience.', 'How would your virtual fashion showroom work? What features would make buyers prefer it to in-person?', 'thought', 'design', fashion_id, 'hard', 5, 35, '["3D Experience Design", "B2B Product", "Virtual Reality"]', '["Creates immersive experience", "Addresses buyer needs", "Shows innovation"]', '{"fun_facts": ["Fashion shows cost $1M+ to produce", "Virtual showrooms reduce carbon footprint 90%", "3D garments are photorealistic now"], "career_connections": ["Virtual Experience Designer", "Fashion Tech Developer", "Digital Showroom Manager"], "company_examples": ["Joor", "NuOrder", "Ordre"]}', 'teen'),
  
  ('Sustainable Score', 'Shoppers want to buy sustainable fashion but can''t easily compare brands. Design a sustainability rating system for fashion brands.', 'Create a scoring system for fashion sustainability. What factors would you measure?', 'decision', 'design', fashion_id, 'medium', 4, 30, '["Rating System Design", "Sustainability Metrics", "Consumer Information"]', '["Lists measurable factors", "Creates clear scoring", "Makes it actionable"]', '{"fun_facts": ["Only 1% of fashion brands are fully transparent", "Good On You rates 3000+ brands", "Sustainability labels increase sales 20%"], "career_connections": ["Sustainability Analyst", "Fashion Rating Developer", "ESG Consultant"], "company_examples": ["Good On You", "Fashion Revolution", "Stand Earth"]}', 'teen'),
  
  ('Size-Inclusive Design', 'Most fashion brands design for sizes 0-12, then just "scale up" for larger sizes. This creates poor fit for plus-size customers.', 'Design a better approach to creating clothes that fit all body types well.', 'thought', 'design', fashion_id, 'medium', 4, 30, '["Inclusive Design", "Product Development", "Customer Empathy"]', '["Proposes inclusive process", "Considers diverse bodies", "Creates practical solution"]', '{"fun_facts": ["68% of American women wear size 14+", "Plus-size fashion market is $32 billion", "Inclusive brands grow 2x faster"], "career_connections": ["Inclusive Design Lead", "Fashion Product Developer", "Size-Inclusive Consultant"], "company_examples": ["Universal Standard", "Girlfriend Collective", "Savage X Fenty"]}', 'teen'),
  
  ('Closet Organizer App', 'People forget what clothes they own and keep buying similar items. Design an app that digitizes and organizes their wardrobe.', 'What features would your closet organizer app need to actually change how people shop?', 'thought', 'design', fashion_id, 'medium', 4, 30, '["App Design", "Behavior Change", "Organization"]', '["Lists key features", "Reduces repeat purchases", "Creates habit formation"]', '{"fun_facts": ["Average person has 103 items of clothing", "20% is never worn", "Outfit planning saves 30 minutes daily"], "career_connections": ["Consumer App PM", "Fashion Tech Designer", "Sustainability Product Manager"], "company_examples": ["Whering", "Stylebook", "Acloset"]}', 'teen'),
  
  ('Pop-Up Experience', 'A new sustainable fashion brand wants to create buzz without opening expensive stores. Design an innovative pop-up retail experience.', 'Design a pop-up concept that creates maximum impact with minimum budget.', 'scenario', 'design', fashion_id, 'medium', 4, 30, '["Retail Experience", "Experiential Marketing", "Budget Creativity"]', '["Creates memorable experience", "Works within budget", "Drives brand awareness"]', '{"fun_facts": ["Pop-ups can generate 80% of yearly revenue", "Experience-driven retail grows 5x faster", "Instagram-worthy moments drive 30% more traffic"], "career_connections": ["Retail Experience Designer", "Brand Activation Manager", "Pop-Up Consultant"], "company_examples": ["Appear Here", "Showfields", "Neighborhood Goods"]}', 'teen'),
  
  ('Fashion Waste Tracker', 'Consumers don''t realize how much clothing waste they create. Design a system that makes fashion waste visible and actionable.', 'How would you help people see and reduce their fashion waste footprint?', 'thought', 'design', fashion_id, 'medium', 4, 30, '["Behavior Change", "Data Visualization", "Sustainability"]', '["Makes impact visible", "Provides actionable steps", "Creates motivation"]', '{"fun_facts": ["92 million tons of textile waste yearly", "Average American throws away 81 lbs of clothes", "Less than 1% is recycled into new clothes"], "career_connections": ["Sustainability Product Manager", "Impact Measurement Analyst", "Circular Economy Designer"], "company_examples": ["For Days", "ThredUp", "Fashion Revolution"]}', 'teen'),
  
  ('Custom Fit Platform', 'Mass customization is now possible - clothes made to your exact measurements. Design a platform for custom-fit fashion.', 'Create the user journey for ordering custom-fit clothes online. How does it work?', 'thought', 'design', fashion_id, 'hard', 5, 35, '["User Journey Design", "Customization", "E-commerce"]', '["Maps complete journey", "Simplifies measurement", "Creates confidence"]', '{"fun_facts": ["Custom clothing has 0% returns", "3D body scanning takes 15 seconds", "MTM suits cost 40% less than bespoke"], "career_connections": ["Fashion Tech PM", "Made-to-Order Specialist", "E-commerce Designer"], "company_examples": ["MTailor", "Proper Cloth", "Indochino"]}', 'teen');

  -- BUILD pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('School Thrift Market', 'You want to organize a clothing swap/thrift market at your school. Create a plan to make it happen successfully.', 'Create a step-by-step plan for organizing a school thrift market, from promotion to execution.', 'scenario', 'build', fashion_id, 'medium', 5, 35, '["Event Planning", "Community Building", "Sustainability"]', '["Creates detailed plan", "Includes promotion strategy", "Addresses logistics"]', '{"fun_facts": ["Clothing swaps save average $500/year", "Gen Z drives 40% of thrift market growth", "School events have 3x higher participation"], "career_connections": ["Event Coordinator", "Sustainability Advocate", "Community Organizer"], "company_examples": ["Swapdom", "Swap Society", "Clothing Swap"]}', 'teen'),
  
  ('Fashion Brand Launch', 'You''re launching a small sustainable fashion brand online. Create your first 30-day marketing plan with $500 budget.', 'Map out your 30-day launch plan: What would you do each week and how would you spend the budget?', 'thought', 'build', fashion_id, 'hard', 5, 35, '["Marketing Planning", "Budget Management", "Brand Launch"]', '["Creates weekly timeline", "Allocates budget wisely", "Sets measurable goals"]', '{"fun_facts": ["Most fashion brands spend 5-10% on marketing", "Instagram drives 30% of fashion discovery", "Micro-influencer posts cost $100-500"], "career_connections": ["Fashion Marketing Manager", "Brand Founder", "Digital Marketing Specialist"], "company_examples": ["Glossier", "Everlane", "Outdoor Voices"]}', 'teen'),
  
  ('Wardrobe Audit Service', 'You want to start a business helping people declutter and organize their wardrobes. Create your service offering and pricing.', 'Design your wardrobe audit service: What do you offer, how long does it take, and what do you charge?', 'scenario', 'build', fashion_id, 'medium', 4, 30, '["Service Design", "Pricing Strategy", "Business Planning"]', '["Defines clear service", "Sets reasonable pricing", "Creates value proposition"]', '{"fun_facts": ["Professional organizers charge $50-150/hour", "Wardrobe consulting is a $1B industry", "Marie Kondo created a global movement"], "career_connections": ["Wardrobe Consultant", "Professional Organizer", "Personal Stylist"], "company_examples": ["The Home Edit", "Stylebook", "Trunk Club"]}', 'teen'),
  
  ('Upcycling Workshop', 'You want to teach people how to upcycle old clothes into new items. Plan a workshop that''s both fun and educational.', 'Design a 2-hour upcycling workshop: What will participants make and what''s your teaching plan?', 'thought', 'build', fashion_id, 'easy', 4, 25, '["Workshop Design", "Teaching", "Creative Skills"]', '["Creates clear curriculum", "Chooses achievable project", "Includes materials list"]', '{"fun_facts": ["Upcycled fashion is worth $40 billion", "Basic sewing skills can save $1000/year", "70% of upcyclers started during COVID"], "career_connections": ["Workshop Facilitator", "Upcycling Artist", "Sustainability Educator"], "company_examples": ["Patagonia Worn Wear", "Remade By", "Goodwill"]}', 'teen'),
  
  ('Fashion Instagram Strategy', 'A new sustainable fashion brand has 0 followers. Create a 30-day Instagram content strategy to grow their audience.', 'Create a week-by-week content calendar with post types, themes, and growth tactics.', 'scenario', 'build', fashion_id, 'medium', 5, 35, '["Content Strategy", "Social Media", "Audience Growth"]', '["Creates content calendar", "Mixes content types", "Includes growth tactics"]', '{"fun_facts": ["Fashion brands post 2-3x daily on average", "Reels get 2x more engagement than photos", "Hashtags increase reach by 12%"], "career_connections": ["Social Media Manager", "Content Strategist", "Fashion Marketer"], "company_examples": ["Later", "Planoly", "Hootsuite"]}', 'teen'),
  
  ('Capsule Collection', 'Design a 10-piece capsule collection that all works together. Every item should match with at least 3 others.', 'Plan your 10-piece capsule collection: List each item and explain how they work together.', 'thought', 'build', fashion_id, 'medium', 5, 30, '["Fashion Design", "Cohesive Thinking", "Minimalism"]', '["Lists 10 items", "Explains versatility", "Creates cohesive collection"]', '{"fun_facts": ["Capsule wardrobes create 100+ outfits from 30 pieces", "French women own 10 core items", "Minimalist dressing saves 20 minutes daily"], "career_connections": ["Fashion Designer", "Wardrobe Consultant", "Sustainable Fashion Curator"], "company_examples": ["Cuyana", "COS", "Everlane"]}', 'teen'),
  
  ('Fashion Blog Launch', 'You want to start a fashion blog focused on sustainable style. Plan your first month of content and growth strategy.', 'Create your blog launch plan: What topics will you cover and how will you attract readers?', 'thought', 'build', fashion_id, 'medium', 4, 30, '["Content Creation", "SEO", "Audience Building"]', '["Plans content themes", "Includes SEO strategy", "Has distribution plan"]', '{"fun_facts": ["Fashion is the #2 blog category globally", "Long-form content ranks 3x better", "Pinterest drives 80% of fashion blog traffic"], "career_connections": ["Fashion Blogger", "Content Creator", "Digital Publisher"], "company_examples": ["Who What Wear", "Man Repeller", "The Blonde Salad"]}', 'teen');

  -- EXPLORE pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Shein''s Secret', 'Shein went from unknown to world''s largest fashion retailer in just 10 years, selling millions of items at incredibly low prices.', 'How does Shein sell clothes so cheaply? What are the hidden costs of their business model?', 'thought', 'explore', fashion_id, 'hard', 5, 35, '["Business Analysis", "Ethics", "Supply Chain"]', '["Explains business model", "Identifies hidden costs", "Shows critical thinking"]', '{"fun_facts": ["Shein adds 6000 new styles daily", "Average Shein item costs $7", "Fast fashion workers earn $3/day in some countries"], "career_connections": ["Supply Chain Analyst", "Business Journalist", "Ethics Consultant"], "company_examples": ["Shein", "Fashion Revolution", "Clean Clothes Campaign"]}', 'teen'),
  
  ('Fashion Week Evolution', 'Traditional fashion weeks are being disrupted by digital shows, TikTok trends, and direct-to-consumer brands.', 'Are fashion weeks still relevant? How might they evolve in the next 10 years?', 'thought', 'explore', fashion_id, 'medium', 4, 30, '["Industry Analysis", "Future Thinking", "Media Evolution"]', '["Analyzes current state", "Predicts changes", "Shows industry understanding"]', '{"fun_facts": ["Fashion weeks were invented in 1943", "Digital shows reached 100M+ viewers", "Brands now show collections on TikTok first"], "career_connections": ["Fashion Show Producer", "Industry Analyst", "Fashion Media Executive"], "company_examples": ["CFDA", "British Fashion Council", "Fashion Week Online"]}', 'teen'),
  
  ('Luxury Resale Boom', 'Secondhand luxury is now a $40 billion market. Young people are buying used Gucci and Chanel instead of new fast fashion.', 'Why are young people choosing used luxury over new fast fashion? What does this signal about consumer values?', 'thought', 'explore', fashion_id, 'medium', 4, 30, '["Consumer Behavior", "Luxury Markets", "Trend Analysis"]', '["Identifies motivations", "Shows value shift", "Predicts implications"]', '{"fun_facts": ["Luxury resale growing 12% yearly", "A Birkin bag appreciates faster than gold", "70% of luxury resale buyers are under 35"], "career_connections": ["Luxury Brand Analyst", "Resale Platform PM", "Consumer Researcher"], "company_examples": ["The RealReal", "Vestiaire Collective", "Rebag"]}', 'teen'),
  
  ('Made in Bangladesh', 'Bangladesh is the world''s #2 clothing producer. The Rana Plaza factory collapse killed 1,134 workers in 2013.', 'What has changed in garment worker safety since Rana Plaza? What still needs to improve?', 'thought', 'explore', fashion_id, 'hard', 5, 35, '["Supply Chain Ethics", "Labor Rights", "Industry Change"]', '["Shows research", "Identifies improvements", "Proposes solutions"]', '{"fun_facts": ["4 million Bangladeshi women work in garments", "Minimum wage is $95/month", "The Accord improved safety in 2200 factories"], "career_connections": ["Supply Chain Auditor", "Labor Rights Advocate", "CSR Manager"], "company_examples": ["Fashion Revolution", "Clean Clothes Campaign", "Fair Wear Foundation"]}', 'teen'),
  
  ('Digital Fashion Future', 'People are buying digital-only clothes for their avatars. Brands are selling NFT fashion items for thousands of dollars.', 'Will we wear more digital clothes than physical ones in 20 years? Explain your prediction.', 'thought', 'explore', fashion_id, 'hard', 5, 35, '["Future Thinking", "Digital Trends", "Consumer Behavior"]', '["Makes clear prediction", "Supports with reasoning", "Considers implications"]', '{"fun_facts": ["Digital fashion items sell for $10,000+", "Gaming skins market is $50 billion", "The Fabricant sold first digital couture in 2019"], "career_connections": ["Digital Fashion Designer", "Metaverse Strategist", "NFT Curator"], "company_examples": ["The Fabricant", "RTFKT", "DressX"]}', 'teen'),
  
  ('Zara vs H&M', 'Zara and H&M are the world''s largest fast fashion brands but have very different business models.', 'What makes Zara and H&M different? Which model is better positioned for the future?', 'thought', 'explore', fashion_id, 'medium', 4, 30, '["Competitive Analysis", "Business Strategy", "Retail"]', '["Compares business models", "Identifies key differences", "Predicts winner"]', '{"fun_facts": ["Zara produces 65% in-house, H&M outsources 80%", "Zara restocks twice weekly, H&M monthly", "Both are pivoting to sustainability"], "career_connections": ["Retail Analyst", "Business Strategist", "Fashion Industry Consultant"], "company_examples": ["Inditex", "H&M Group", "McKinsey Fashion"]}', 'teen'),
  
  ('Body Positivity Movement', 'Fashion brands are increasingly featuring diverse body types in advertising. But critics say it''s often "tokenism" not real change.', 'Is the fashion industry truly becoming more inclusive, or is it just marketing? What evidence supports your view?', 'thought', 'explore', fashion_id, 'medium', 4, 30, '["Cultural Analysis", "Marketing Ethics", "Representation"]', '["Takes clear position", "Uses evidence", "Shows nuanced thinking"]', '{"fun_facts": ["Plus-size models in ads increased 300% since 2019", "Only 5% of fashion images show larger bodies", "Inclusive ads generate 25% more engagement"], "career_connections": ["Diversity & Inclusion Consultant", "Fashion Media Analyst", "Brand Ethics Advisor"], "company_examples": ["Chromat", "Aerie", "Savage X Fenty"]}', 'teen');

  -- ============ AVIATION & EVENTS TRACK (30 challenges) ============
  
  -- DISCOVER pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Drone Show Magic', 'Dubai''s drone shows use 1,500+ drones dancing in perfect sync to create images in the sky. It takes massive coordination and technology.', 'What problems had to be solved to make synchronized drone shows possible?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Technology Analysis", "Problem Identification", "Systems Thinking"]', '["Identifies technical challenges", "Shows understanding of coordination", "Lists solved problems"]', '{"fun_facts": ["Drones communicate 200 times per second", "One show requires 50+ operators", "GPS accuracy must be within 1cm"], "career_connections": ["Drone Show Engineer", "Event Technology Director", "Autonomous Systems Developer"], "company_examples": ["SKYMAGIC", "Intel Drone Light Shows", "Dronisos"]}', 'teen'),
  
  ('Airport Bottleneck', 'Dubai Airport handles 90 million passengers yearly - but check-in, security, and immigration create long queues.', 'What''s the biggest bottleneck in airport passenger flow? How would you research this?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Process Analysis", "Customer Journey", "Research Design"]', '["Identifies bottleneck", "Proposes research method", "Shows systems thinking"]', '{"fun_facts": ["Average passenger spends 2 hours at airport before flight", "Biometric gates are 3x faster than manual", "Smart airports can predict queues 4 hours ahead"], "career_connections": ["Airport Operations Analyst", "UX Researcher", "Aviation Consultant"], "company_examples": ["SITA", "Amadeus", "Collins Aerospace"]}', 'teen'),
  
  ('Event Crowd Mystery', 'Stadium events with 50,000+ people create dangerous crowd situations. Understanding crowd behavior can save lives.', 'How do people behave differently in large crowds vs small groups? What patterns emerge?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Crowd Psychology", "Safety Research", "Behavioral Analysis"]', '["Identifies behavior patterns", "Shows safety awareness", "Proposes research approach"]', '{"fun_facts": ["Crowd density over 4 people/sqm is dangerous", "Panic is rare - crowds are usually orderly", "AI can predict crush points 20 minutes ahead"], "career_connections": ["Crowd Safety Consultant", "Event Operations Manager", "Human Factors Engineer"], "company_examples": ["Crowd Dynamics", "STAC", "Counterflow"]}', 'teen'),
  
  ('Flying Car Reality', 'Companies are developing "air taxis" - vertical takeoff vehicles for urban transport. Dubai wants to be first to launch them.', 'What are the biggest obstacles preventing flying cars from becoming reality?', 'thought', 'discover', aviation_id, 'hard', 4, 30, '["Technology Assessment", "Regulatory Analysis", "Future Mobility"]', '["Lists key obstacles", "Considers multiple factors", "Shows realistic assessment"]', '{"fun_facts": ["100+ companies are developing air taxis", "Joby aims to launch in 2024", "Air taxi rides could cost $3-5 per mile"], "career_connections": ["Urban Air Mobility Engineer", "Aviation Regulatory Specialist", "Future Mobility Analyst"], "company_examples": ["Joby Aviation", "Lilium", "Archer"]}', 'teen'),
  
  ('Lost Luggage Problem', 'Airlines lose 25 million bags per year. Reuniting passengers with luggage costs billions and causes massive frustration.', 'Why do airlines still lose luggage when we can track packages in real-time? What''s different?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Logistics Analysis", "System Comparison", "Problem Root Cause"]', '["Compares systems", "Identifies unique challenges", "Shows analytical thinking"]', '{"fun_facts": ["RFID tags could eliminate 25% of lost bags", "Most bags are delayed, not truly lost", "Airlines pay $30-50 per mishandled bag"], "career_connections": ["Aviation Logistics Manager", "RFID Systems Engineer", "Baggage Operations Director"], "company_examples": ["SITA BagJourney", "Zebra Technologies", "Amadeus"]}', 'teen'),
  
  ('Festival Power', 'Large music festivals consume as much electricity as a small town. Most rely on diesel generators, creating pollution.', 'What are the biggest energy challenges facing music festivals?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Energy Analysis", "Event Operations", "Sustainability"]', '["Identifies energy needs", "Lists challenges", "Shows scale understanding"]', '{"fun_facts": ["Glastonbury uses 25,000 liters of diesel", "Solar festivals exist but are rare", "Battery storage is revolutionizing event power"], "career_connections": ["Event Sustainability Manager", "Renewable Energy Consultant", "Festival Operations Director"], "company_examples": ["Firefly Clean Energy", "ZeroWaste Events", "U Power"]}', 'teen'),
  
  ('In-Flight Experience Gap', 'Airplane seats haven''t fundamentally changed in 50 years. Despite technology advances, flying is still uncomfortable for most.', 'Why hasn''t the airplane seat experience improved more? What''s preventing innovation?', 'thought', 'discover', aviation_id, 'medium', 4, 30, '["Industry Analysis", "Innovation Barriers", "Customer Experience"]', '["Identifies innovation barriers", "Shows industry understanding", "Considers stakeholders"]', '{"fun_facts": ["Seat pitch has shrunk 4 inches since 1990", "Aircraft seats cost $10,000-$100,000 each", "Certification for new seats takes 3+ years"], "career_connections": ["Aircraft Interior Designer", "Aviation UX Researcher", "Seat Manufacturer PM"], "company_examples": ["Recaro", "Collins Aerospace", "Safran Seats"]}', 'teen'),
  
  ('Virtual Event Fatigue', 'After COVID, virtual events boomed. But attendance and engagement have dropped as people tired of Zoom.', 'What makes virtual events feel draining? What would make them more engaging?', 'thought', 'discover', aviation_id, 'easy', 3, 25, '["User Research", "Digital Experience", "Engagement Analysis"]', '["Identifies fatigue causes", "Proposes solutions", "Shows user empathy"]', '{"fun_facts": ["Virtual event attention span is 8 minutes", "Hybrid events have 3x the reach", "Gaming platforms have better engagement"], "career_connections": ["Virtual Event Producer", "Digital Experience Designer", "Event Technology Strategist"], "company_examples": ["Hopin", "Run The World", "Gather"]}', 'teen');

  -- DESIGN pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Smart Airport Wayfinding', 'Passengers get lost in large airports, missing flights and causing stress. Design a smart navigation system.', 'Design an airport navigation app that guides passengers from arrival to gate. What key features would it have?', 'thought', 'design', aviation_id, 'medium', 5, 35, '["App Design", "Navigation UX", "Passenger Experience"]', '["Proposes key features", "Solves real problems", "Creates seamless experience"]', '{"fun_facts": ["15% of passengers miss flights due to navigation issues", "Indoor GPS is now accurate to 1 meter", "AR navigation increases wayfinding speed 40%"], "career_connections": ["Airport UX Designer", "Navigation App PM", "Aviation Tech Developer"], "company_examples": ["LocusLabs", "Pointr", "Situm"]}', 'teen'),
  
  ('Crowd Flow System', 'A 60,000-seat stadium needs to evacuate safely in emergencies. Design a smart crowd management system.', 'How would your AI-powered crowd management system work? What would it monitor and control?', 'thought', 'design', aviation_id, 'hard', 5, 35, '["Safety System Design", "AI Application", "Emergency Planning"]', '["Creates monitoring system", "Includes AI elements", "Ensures safety"]', '{"fun_facts": ["Stadium evacuation should take under 8 minutes", "Cameras can count crowd density in real-time", "Dynamic signage can redirect crowd flow"], "career_connections": ["Safety Systems Engineer", "Crowd Analytics PM", "Stadium Operations Director"], "company_examples": ["Crowd Connected", "Risktal", "Unnanu"]}', 'teen'),
  
  ('Sustainable Air Travel', 'Airlines want to reduce carbon emissions but planes still run on jet fuel. Design an offset/sustainability program for passengers.', 'Design a carbon offset program that passengers would actually use. How would it work?', 'scenario', 'design', aviation_id, 'medium', 4, 30, '["Program Design", "Sustainability", "Behavior Change"]', '["Creates engaging program", "Makes it easy to use", "Ensures real impact"]', '{"fun_facts": ["2% of global emissions come from aviation", "Sustainable aviation fuel costs 2-4x more", "Only 1% of passengers voluntarily offset"], "career_connections": ["Airline Sustainability Manager", "Carbon Program Designer", "ESG Consultant"], "company_examples": ["CHOOOSE", "South Pole", "Neste"]}', 'teen'),
  
  ('Interactive Event Experience', 'Conferences are boring - speakers talk, audience listens. Design an interactive conference experience.', 'Reimagine the conference experience: How would you make it truly interactive and memorable?', 'thought', 'design', aviation_id, 'medium', 4, 30, '["Experience Design", "Engagement", "Event Innovation"]', '["Creates interactive elements", "Increases engagement", "Shows innovation"]', '{"fun_facts": ["Attention drops 50% after 10 minutes", "Interactive sessions have 4x recall", "Mobile apps increase event engagement 45%"], "career_connections": ["Event Experience Designer", "Conference Producer", "Engagement Strategist"], "company_examples": ["Slido", "Mentimeter", "Bizzabo"]}', 'teen'),
  
  ('Drone Delivery Network', 'Dubai wants a network of drones delivering packages across the city. Design the system architecture.', 'Design a city-wide drone delivery network: Where would hubs be? How would it work?', 'thought', 'design', aviation_id, 'hard', 5, 35, '["Network Design", "Logistics", "Urban Planning"]', '["Plans network structure", "Addresses logistics", "Considers regulations"]', '{"fun_facts": ["Wing has made 200,000+ drone deliveries", "Drones can deliver in 30 minutes vs 2 hours", "Dubai approved drone delivery corridors in 2022"], "career_connections": ["Drone Network Planner", "Urban Mobility Designer", "Logistics Architect"], "company_examples": ["Wing", "Matternet", "Zipline"]}', 'teen'),
  
  ('Boarding Innovation', 'Airplane boarding takes 25+ minutes and frustrates everyone. Multiple methods have been tried but none solved it.', 'Design a new boarding process that gets passengers seated in under 15 minutes.', 'thought', 'design', aviation_id, 'medium', 4, 30, '["Process Design", "Passenger Experience", "Efficiency"]', '["Creates new process", "Reduces time", "Considers passenger experience"]', '{"fun_facts": ["Random boarding is fastest in simulations", "Airlines lose $30 per minute of delay", "Southwest uses open seating and boards faster"], "career_connections": ["Airline Operations Designer", "Process Engineer", "Customer Experience Lead"], "company_examples": ["Southwest Airlines", "Boeing", "Airbus"]}', 'teen'),
  
  ('VIP Airport Experience', 'First-class passengers want a seamless, personalized airport experience. Design a premium journey.', 'Design the ultimate VIP airport experience: From arrival to boarding, what would make it special?', 'scenario', 'design', aviation_id, 'medium', 4, 30, '["Luxury Experience", "Service Design", "Personalization"]', '["Creates premium touches", "Shows personalization", "Addresses all touchpoints"]', '{"fun_facts": ["VIP terminals charge $3000+ per visit", "Biometrics eliminate all queues for VIPs", "Personal hosts guide VIPs through airports"], "career_connections": ["VIP Services Director", "Luxury Experience Designer", "Premium Travel Consultant"], "company_examples": ["The Private Suite LAX", "Emirates First Class", "Qatar Premium Terminal"]}', 'teen'),
  
  ('Festival App', 'Music festivals have apps but they''re usually bad. Design the ultimate festival companion app.', 'What 5 features would make a festival app actually indispensable for attendees?', 'decision', 'design', aviation_id, 'easy', 4, 25, '["App Design", "Festival Experience", "User Needs"]', '["Lists 5 specific features", "Solves real problems", "Creates engagement"]', '{"fun_facts": ["70% of festival goers use event apps", "Real-time crowd maps reduce congestion 30%", "Cashless payments speed up purchases 3x"], "career_connections": ["Event App PM", "Festival Tech Director", "UX Designer"], "company_examples": ["Festicket", "BottleRock", "Eventbase"]}', 'teen');

  -- BUILD pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('School Event Plan', 'You''re organizing a 500-person school event. Create a detailed event plan from start to finish.', 'Create your event master plan: Timeline, roles, budget allocation, and contingencies.', 'scenario', 'build', aviation_id, 'medium', 5, 35, '["Event Planning", "Project Management", "Resource Allocation"]', '["Creates detailed timeline", "Assigns roles", "Plans contingencies"]', '{"fun_facts": ["Event planning is a $1 trillion industry", "Checklists reduce event errors by 50%", "Most events need 3-6 months planning"], "career_connections": ["Event Planner", "Project Manager", "Operations Coordinator"], "company_examples": ["Cvent", "Eventbrite", "Social Tables"]}', 'teen'),
  
  ('Drone Demo Pitch', 'You want to convince your school to use drones for an outdoor event. Create a persuasive pitch.', 'What 5 key points would you make to convince school administrators to approve a drone demonstration?', 'decision', 'build', aviation_id, 'medium', 4, 30, '["Persuasion", "Presentation", "Stakeholder Management"]', '["Lists 5 key points", "Addresses concerns", "Shows benefits clearly"]', '{"fun_facts": ["Drone shows are 50% cheaper than fireworks", "Zero fire risk compared to pyrotechnics", "Educational drones cost $100-500"], "career_connections": ["Drone Services Sales", "Event Technology Consultant", "School Tech Coordinator"], "company_examples": ["DJI Education", "Parrot", "Skydio"]}', 'teen'),
  
  ('Virtual Conference Kit', 'Your school is hosting a virtual conference for 200 students. Create the tech setup and run-of-show.', 'Plan your virtual conference: What platforms, what schedule, and how will you keep people engaged?', 'scenario', 'build', aviation_id, 'medium', 5, 35, '["Virtual Event Production", "Technology Planning", "Engagement"]', '["Chooses right platforms", "Creates engaging schedule", "Plans for tech issues"]', '{"fun_facts": ["Breakout rooms increase engagement 60%", "Virtual events need 3x more moderators", "Average virtual event attention is 52 minutes"], "career_connections": ["Virtual Event Producer", "Tech Operations Manager", "Digital Event Coordinator"], "company_examples": ["Hopin", "Zoom Events", "Airmeet"]}', 'teen'),
  
  ('Airport Service Recovery', 'A flight is cancelled and 200 passengers are stranded. Create a service recovery playbook.', 'What steps would you take to handle 200 stranded passengers and turn a crisis into a positive experience?', 'scenario', 'build', aviation_id, 'hard', 5, 35, '["Crisis Management", "Customer Service", "Operations"]', '["Creates step-by-step plan", "Prioritizes needs", "Includes communication"]', '{"fun_facts": ["Good service recovery increases loyalty 15%", "Proactive communication reduces complaints 50%", "Food/drink vouchers are most appreciated"], "career_connections": ["Airline Operations Manager", "Customer Experience Lead", "Crisis Management Specialist"], "company_examples": ["Southwest", "Singapore Airlines", "JetBlue"]}', 'teen'),
  
  ('Sports Event Logistics', 'You''re planning the logistics for a school sports tournament with 500 athletes from 10 schools.', 'Create your tournament logistics plan: Registration, scheduling, facilities, and communication.', 'thought', 'build', aviation_id, 'medium', 5, 35, '["Sports Event Planning", "Logistics", "Multi-Stakeholder Management"]', '["Plans registration system", "Creates schedule", "Coordinates facilities"]', '{"fun_facts": ["Sports events require 1 staff per 50 participants", "Weather contingencies are essential", "Clear communication prevents 80% of issues"], "career_connections": ["Sports Event Manager", "Athletic Director", "Tournament Coordinator"], "company_examples": ["LeagueApps", "TeamSnap", "SportsEngine"]}', 'teen'),
  
  ('Ticketing System', 'Your school talent show needs an online ticketing system. Set up and launch ticket sales.', 'Design your ticketing strategy: Pricing tiers, early bird offers, and promotion plan.', 'thought', 'build', aviation_id, 'easy', 4, 25, '["Ticketing", "Pricing Strategy", "Marketing"]', '["Creates pricing tiers", "Plans promotion", "Sets up sales"]', '{"fun_facts": ["Early bird pricing increases sales 30%", "Limited tickets create urgency", "Social sharing increases reach 5x"], "career_connections": ["Box Office Manager", "Event Marketing Coordinator", "Ticketing Operations"], "company_examples": ["Eventbrite", "Ticketmaster", "Universe"]}', 'teen'),
  
  ('Hybrid Event Guide', 'Create a guide for running hybrid events (in-person + virtual simultaneously).', 'What are the 5 biggest challenges of hybrid events and how would you solve each one?', 'decision', 'build', aviation_id, 'hard', 5, 35, '["Hybrid Event Production", "Problem Solving", "Technology"]', '["Identifies 5 challenges", "Proposes solutions", "Shows practical approach"]', '{"fun_facts": ["Hybrid events have 3x the reach of in-person", "Virtual attendees need different content pacing", "Audio quality is the #1 technical challenge"], "career_connections": ["Hybrid Event Producer", "AV Technical Director", "Event Strategist"], "company_examples": ["Cvent", "ON24", "6Connex"]}', 'teen');

  -- EXPLORE pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Supersonic Return', 'Concorde retired in 2003. Now multiple companies are building new supersonic jets. The technology exists but...', 'Why did supersonic commercial flight fail, and what has changed to make companies try again?', 'thought', 'explore', aviation_id, 'hard', 5, 35, '["Aviation History", "Business Analysis", "Technology Evolution"]', '["Explains Concorde failure", "Identifies what changed", "Shows industry understanding"]', '{"fun_facts": ["Concorde flew NYC-London in 3 hours", "Sonic boom restricted routes to over-ocean only", "Boom Supersonic has 130 aircraft orders"], "career_connections": ["Aviation Analyst", "Aerospace Engineer", "Industry Historian"], "company_examples": ["Boom Supersonic", "Aerion", "Spike Aerospace"]}', 'teen'),
  
  ('Emirates Success Story', 'Emirates went from 2 aircraft in 1985 to 270+ today, becoming one of the world''s best airlines.', 'What strategic decisions made Emirates succeed while other airlines failed?', 'thought', 'explore', aviation_id, 'medium', 4, 30, '["Business Strategy", "Competitive Analysis", "Industry Study"]', '["Identifies key strategies", "Shows competitive analysis", "Explains success factors"]', '{"fun_facts": ["Emirates has never had an unprofitable year", "Dubai Hub strategy created 180,000 jobs", "Emirates was the first airline with in-seat screens"], "career_connections": ["Airline Strategist", "Business Analyst", "Aviation Consultant"], "company_examples": ["Emirates", "Qatar Airways", "Singapore Airlines"]}', 'teen'),
  
  ('Space Tourism Arrival', 'Blue Origin and Virgin Galactic now offer space tourism flights. The industry is just beginning.', 'Will space tourism become mainstream in our lifetime? What needs to happen for mass adoption?', 'thought', 'explore', aviation_id, 'hard', 5, 35, '["Future Analysis", "Technology Adoption", "Economics"]', '["Predicts timeline", "Identifies requirements", "Shows realistic assessment"]', '{"fun_facts": ["Space tourism tickets cost $250,000-$450,000", "Over 700 people have reserved seats", "SpaceX plans orbital hotels by 2027"], "career_connections": ["Space Tourism Analyst", "Aerospace Business Developer", "Future Mobility Strategist"], "company_examples": ["Blue Origin", "Virgin Galactic", "SpaceX"]}', 'teen'),
  
  ('Live Event Future', 'Despite streaming, live events are booming. Concerts, sports, and festivals are selling out.', 'Why do people still pay premium prices for live events when they could watch from home?', 'thought', 'explore', aviation_id, 'medium', 4, 30, '["Consumer Psychology", "Experience Economy", "Event Industry"]', '["Explains emotional drivers", "Identifies experience factors", "Shows consumer understanding"]', '{"fun_facts": ["Live event spending up 70% since 2010", "FOMO drives 60% of ticket purchases", "Experiences are valued 4x more than objects by Gen Z"], "career_connections": ["Event Industry Analyst", "Experience Economy Researcher", "Entertainment Consultant"], "company_examples": ["Live Nation", "AEG", "MSG Entertainment"]}', 'teen'),
  
  ('Aviation & Climate', 'Aviation produces 2% of global emissions but is growing fast. The industry needs to decarbonize.', 'How will aviation become carbon-neutral? What technologies and changes are most promising?', 'thought', 'explore', aviation_id, 'hard', 5, 35, '["Climate Solutions", "Aviation Technology", "Industry Transformation"]', '["Lists key technologies", "Assesses feasibility", "Shows timeline understanding"]', '{"fun_facts": ["Sustainable aviation fuel reduces emissions 80%", "Electric planes limited to 500km currently", "Hydrogen aircraft testing begins in 2025"], "career_connections": ["Aviation Sustainability Manager", "Clean Tech Analyst", "Aerospace Engineer"], "company_examples": ["ZeroAvia", "Heart Aerospace", "Universal Hydrogen"]}', 'teen'),
  
  ('Airport City Concept', 'Major airports are becoming "airport cities" with hotels, offices, malls, and entertainment - not just transit points.', 'Why are airports evolving into cities? What''s driving this transformation?', 'thought', 'explore', aviation_id, 'medium', 4, 30, '["Urban Development", "Aviation Business", "Commercial Strategy"]', '["Explains business model", "Identifies drivers", "Shows commercial understanding"]', '{"fun_facts": ["Singapore Changi has a butterfly garden and waterfall", "Airport retail is $45 billion annually", "50% of airport revenue now comes from non-aviation"], "career_connections": ["Airport Development Manager", "Commercial Strategy Analyst", "Urban Planner"], "company_examples": ["Singapore Changi", "Amsterdam Schiphol", "Incheon Airport"]}', 'teen'),
  
  ('Events & Mental Health', 'Research shows live events improve mental health, reduce loneliness, and increase happiness.', 'How do live events impact mental health and community building? Why does this matter?', 'thought', 'explore', aviation_id, 'easy', 3, 25, '["Health Research", "Community Building", "Social Impact"]', '["Explains mental health benefits", "Connects to community", "Shows broader impact"]', '{"fun_facts": ["Concert-goers report 21% higher wellbeing", "Shared experiences create stronger memories", "Post-COVID event attendance linked to reduced anxiety"], "career_connections": ["Event Wellness Consultant", "Community Experience Designer", "Social Impact Researcher"], "company_examples": ["Eventbrite", "Culture Trip", "Sofar Sounds"]}', 'teen');

  -- ============ GAMING & ENTERTAINMENT TRACK (30 challenges) ============
  
  -- DISCOVER pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Why Games Are Addictive', 'Games like Fortnite and Roblox keep players engaged for hours. They use specific psychology techniques.', 'What psychology principles make games so engaging? Are they ethical?', 'thought', 'discover', gaming_id, 'medium', 4, 30, '["Game Psychology", "Behavior Design", "Ethics"]', '["Identifies engagement techniques", "Questions ethics", "Shows understanding"]', '{"fun_facts": ["Variable rewards are more addictive than consistent ones", "The average gamer plays 8.5 hours per week", "Fortnite made $9 billion through free-to-play"], "career_connections": ["Game Designer", "Behavioral Psychologist", "UX Researcher"], "company_examples": ["Epic Games", "Supercell", "Zynga"]}', 'teen'),
  
  ('Streaming Economy', 'Top streamers earn millions playing games while most earn nothing. The creator economy is extremely unequal.', 'What determines which streamers succeed? Is it skill, personality, or something else?', 'thought', 'discover', gaming_id, 'medium', 4, 30, '["Creator Economy", "Platform Analysis", "Success Factors"]', '["Identifies success factors", "Analyzes platform dynamics", "Shows creator understanding"]', '{"fun_facts": ["Top 1% of streamers earn 50% of revenue", "Consistency matters more than skill", "Average streamer has 4 viewers"], "career_connections": ["Content Creator", "Talent Manager", "Platform Strategist"], "company_examples": ["Twitch", "YouTube Gaming", "TikTok Live"]}', 'teen'),
  
  ('Esports Audience Gap', 'Esports has 500M viewers but still struggles to attract mainstream sponsors like traditional sports.', 'Why don''t traditional brands sponsor esports as much as traditional sports?', 'thought', 'discover', gaming_id, 'medium', 4, 30, '["Sports Business", "Marketing", "Industry Analysis"]', '["Identifies barriers", "Compares audiences", "Shows market understanding"]', '{"fun_facts": ["Esports revenue is $1.3B vs NFL''s $17B", "Average esports viewer is 26 years old", "Endemic brands sponsor 80% of esports"], "career_connections": ["Esports Marketing Manager", "Brand Partnership Lead", "Sports Business Analyst"], "company_examples": ["Riot Games", "ESL", "Gen.G"]}', 'teen'),
  
  ('AI in Game Creation', 'AI can now generate game assets, write code, and even design levels. Some say this threatens game developers.', 'How will AI change the way games are made? Who benefits and who loses?', 'thought', 'discover', gaming_id, 'hard', 4, 30, '["AI Impact", "Industry Disruption", "Future of Work"]', '["Analyzes AI capabilities", "Identifies winners/losers", "Shows balanced view"]', '{"fun_facts": ["AI can generate game art in seconds vs days", "Roblox uses AI to generate 3D worlds from text", "Some studios cut art teams 50% using AI"], "career_connections": ["AI Game Developer", "Creative Director", "Game Artist"], "company_examples": ["Scenario.gg", "Ludo.ai", "Promethean AI"]}', 'teen'),
  
  ('Mobile vs Console', 'Mobile gaming generates more revenue than console and PC combined. But "serious" gamers look down on mobile.', 'Why does mobile gaming make more money but get less respect?', 'thought', 'discover', gaming_id, 'medium', 4, 30, '["Market Analysis", "Consumer Behavior", "Platform Economics"]', '["Explains revenue model", "Analyzes perception gap", "Shows market understanding"]', '{"fun_facts": ["Mobile is 52% of gaming revenue", "Free-to-play dominates mobile", "Average mobile game session is 7 minutes"], "career_connections": ["Mobile Game PM", "Market Analyst", "Monetization Designer"], "company_examples": ["King", "Supercell", "Tencent"]}', 'teen'),
  
  ('Gaming & Learning', 'Games teach complex skills - strategy, collaboration, resource management. But schools rarely use games for learning.', 'Why don''t schools use games more for education? What''s holding them back?', 'thought', 'discover', gaming_id, 'easy', 3, 25, '["EdTech", "Game-Based Learning", "Adoption Barriers"]', '["Identifies barriers", "Shows educational potential", "Proposes solutions"]', '{"fun_facts": ["Minecraft Education has 35M+ users", "Game-based learning improves retention 90%", "Teachers lack training in educational games"], "career_connections": ["Educational Game Designer", "EdTech Product Manager", "Learning Experience Designer"], "company_examples": ["Minecraft Education", "Kahoot", "Duolingo"]}', 'teen'),
  
  ('Toxicity Problem', 'Online games have a toxicity problem - harassment, hate speech, and bullying are common.', 'Why are some gaming communities so toxic? What would actually reduce toxicity?', 'thought', 'discover', gaming_id, 'medium', 4, 30, '["Community Psychology", "Safety", "Behavior Design"]', '["Identifies causes", "Proposes solutions", "Shows community understanding"]', '{"fun_facts": ["74% of gamers experience harassment", "Anonymity increases toxic behavior 4x", "Good moderation reduces toxicity 40%"], "career_connections": ["Community Manager", "Trust & Safety Lead", "Player Experience Designer"], "company_examples": ["Riot Games", "Discord", "Twitch"]}', 'teen'),
  
  ('Metaverse Hype', 'Companies invested billions in the "metaverse" but adoption has been slow. Virtual worlds exist but aren''t mainstream.', 'Why hasn''t the metaverse taken off? What''s missing?', 'thought', 'discover', gaming_id, 'hard', 4, 30, '["Technology Adoption", "Virtual Worlds", "Market Analysis"]', '["Identifies missing elements", "Analyzes adoption barriers", "Shows realistic assessment"]', '{"fun_facts": ["Meta lost $13 billion on metaverse in 2022", "VR headset adoption is 2% of population", "Roblox and Fortnite are closest to metaverse"], "career_connections": ["Metaverse Strategist", "VR/AR Developer", "Virtual World Designer"], "company_examples": ["Meta", "Epic Games", "Roblox"]}', 'teen');

  -- DESIGN pillar (8 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Educational Game Concept', 'You''re designing a game that teaches financial literacy to teenagers. It needs to be fun AND educational.', 'Design your financial literacy game: What''s the core gameplay loop and how does learning happen?', 'thought', 'design', gaming_id, 'medium', 5, 35, '["Game Design", "Learning Design", "Engagement"]', '["Creates fun gameplay", "Integrates learning", "Shows game design thinking"]', '{"fun_facts": ["Games can teach finance 3x better than textbooks", "Simulation games create lasting behavior change", "Gamification increases engagement 48%"], "career_connections": ["Educational Game Designer", "Learning Experience Designer", "EdTech PM"], "company_examples": ["BitLife", "AdVenture Capitalist", "Cashflow"]}', 'teen'),
  
  ('Anti-Toxicity System', 'Design a system that reduces toxicity in online games without ruining the experience for everyone.', 'How would your anti-toxicity system work? What would it detect and what consequences would it have?', 'thought', 'design', gaming_id, 'hard', 5, 35, '["Safety Design", "Behavior Systems", "Community Management"]', '["Creates detection system", "Designs fair consequences", "Maintains good experience"]', '{"fun_facts": ["AI can detect toxic speech with 90% accuracy", "Positive reinforcement works better than punishment", "Riot''s Honor system reduced toxicity 30%"], "career_connections": ["Trust & Safety Designer", "Community Systems Engineer", "Player Behavior Analyst"], "company_examples": ["Riot Games", "Discord", "Xbox"]}', 'teen'),
  
  ('Accessible Game Controller', 'Many people with disabilities can''t play games with standard controllers. Design an accessible controller.', 'Design a controller that works for gamers with limited hand mobility. What features would it have?', 'thought', 'design', gaming_id, 'medium', 5, 35, '["Accessible Design", "Hardware", "Inclusive Gaming"]', '["Creates accessible features", "Considers diverse needs", "Shows empathy"]', '{"fun_facts": ["400 million gamers have disabilities", "Xbox Adaptive Controller costs $99", "Voice control enables hands-free gaming"], "career_connections": ["Accessible Product Designer", "Gaming Hardware Engineer", "Inclusive Design Consultant"], "company_examples": ["Microsoft", "Logitech G", "SpecialEffect"]}', 'teen'),
  
  ('Streaming Overlay', 'Streamers use overlays to show alerts, chat, and branding. Design a streamer toolkit for beginners.', 'Design a beginner-friendly streaming overlay system. What elements would it include?', 'thought', 'design', gaming_id, 'easy', 4, 25, '["UI Design", "Streaming Tech", "Creator Tools"]', '["Includes key elements", "Makes it easy to use", "Looks professional"]', '{"fun_facts": ["83% of successful streamers use custom overlays", "Alerts increase engagement 25%", "Chat integration is essential for interaction"], "career_connections": ["Streaming Tools PM", "UI Designer", "Creator Platform Developer"], "company_examples": ["Streamlabs", "OBS", "StreamElements"]}', 'teen'),
  
  ('Esports Arena', 'Design a purpose-built esports arena for 5,000 spectators that rivals traditional sports venues.', 'What unique features would your esports arena have that traditional sports venues don''t?', 'thought', 'design', gaming_id, 'hard', 5, 35, '["Venue Design", "Esports Experience", "Architecture"]', '["Proposes unique features", "Considers spectator experience", "Shows esports understanding"]', '{"fun_facts": ["Esports arenas are smaller but more tech-heavy", "Every seat needs a screen view", "Sound design is crucial for atmosphere"], "career_connections": ["Esports Venue Designer", "Experience Architect", "Event Technology Director"], "company_examples": ["Esports Stadium Arlington", "Fnatic Arena", "Gen.G Tigers"]}', 'teen'),
  
  ('Game Monetization', 'Design a fair monetization system for a free-to-play game that makes money without being exploitative.', 'Create a monetization model that players would consider fair. What would you sell and avoid selling?', 'thought', 'design', gaming_id, 'hard', 5, 35, '["Business Model", "Ethics", "Game Economy"]', '["Creates fair model", "Identifies red lines", "Balances profit/player respect"]', '{"fun_facts": ["Cosmetics-only monetization is most accepted", "Loot boxes are banned in some countries", "2% of players generate 80% of revenue"], "career_connections": ["Monetization Designer", "Game Economist", "Product Manager"], "company_examples": ["Riot Games", "Epic Games", "Valve"]}', 'teen'),
  
  ('Virtual Concert', 'Design a virtual concert experience in a game world that feels as exciting as being there in person.', 'How would you design a virtual concert that''s better than watching a video but different from real life?', 'thought', 'design', gaming_id, 'medium', 5, 35, '["Virtual Experience", "Music Tech", "Engagement Design"]', '["Creates unique experience", "Leverages virtual possibilities", "Maintains social feeling"]', '{"fun_facts": ["Travis Scott''s Fortnite concert had 27M viewers", "Virtual concerts eliminate venue limits", "Avatar customization adds personal expression"], "career_connections": ["Virtual Event Designer", "Music Tech PM", "Experience Engineer"], "company_examples": ["Fortnite", "Roblox", "Wave"]}', 'teen'),
  
  ('Parent Gaming Dashboard', 'Parents worry about their kids'' gaming habits. Design a dashboard that helps parents without spying on kids.', 'Design a parental control system that builds trust between parents and kids around gaming.', 'thought', 'design', gaming_id, 'medium', 4, 30, '["Family Tech", "Privacy", "Trust Building"]', '["Balances oversight/privacy", "Builds communication", "Respects kids"]', '{"fun_facts": ["72% of parents worry about gaming time", "Kids who discuss games with parents game more healthily", "Heavy-handed controls often backfire"], "career_connections": ["Family Tech PM", "Child Safety Designer", "UX Researcher"], "company_examples": ["Nintendo", "Xbox Family Settings", "Bark"]}', 'teen');

  -- BUILD pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Game Design Document', 'You have an idea for a mobile game. Create the initial game design document that explains your concept.', 'Write a one-page game design document: Core loop, target audience, unique selling point.', 'scenario', 'build', gaming_id, 'medium', 5, 35, '["Game Design", "Documentation", "Communication"]', '["Explains core loop", "Defines audience", "States unique value"]', '{"fun_facts": ["Most game ideas fail at the design doc stage", "Successful docs are under 5 pages initially", "Core loop clarity predicts success"], "career_connections": ["Game Designer", "Creative Director", "Producer"], "company_examples": ["Supercell", "Rovio", "King"]}', 'teen'),
  
  ('Esports Tournament', 'You''re organizing an esports tournament at your school for 32 players. Create the tournament plan.', 'Plan your esports tournament: Format, schedule, rules, prizes, and promotion strategy.', 'thought', 'build', gaming_id, 'medium', 5, 35, '["Event Planning", "Esports Operations", "Tournament Design"]', '["Creates tournament format", "Plans logistics", "Includes promotion"]', '{"fun_facts": ["Double elimination is fairest format", "Prize pools motivate participation", "School esports programs grew 500% since 2018"], "career_connections": ["Esports Tournament Organizer", "Event Manager", "Community Coordinator"], "company_examples": ["NASEF", "PlayVS", "High School Esports League"]}', 'teen'),
  
  ('YouTube Gaming Channel', 'Launch plan for a gaming YouTube channel. Map out your first 30 days of content.', 'Create your YouTube channel launch plan: Niche, content schedule, and growth tactics for month 1.', 'scenario', 'build', gaming_id, 'medium', 5, 35, '["Content Creation", "YouTube Strategy", "Channel Building"]', '["Defines niche", "Creates content calendar", "Plans growth tactics"]', '{"fun_facts": ["Consistency beats quality in early growth", "First 48 hours determine video success", "Gaming is YouTube''s largest category"], "career_connections": ["YouTuber", "Content Strategist", "Video Producer"], "company_examples": ["PewDiePie", "MrBeast Gaming", "Dream"]}', 'teen'),
  
  ('Game Pitch Deck', 'You need to pitch your game idea to publishers. Create the key slides for your pitch deck.', 'What 6 slides would you include in your game pitch, and what''s the one key message per slide?', 'decision', 'build', gaming_id, 'hard', 5, 35, '["Pitch Skills", "Game Publishing", "Communication"]', '["Creates 6 compelling slides", "Includes key information", "Tells clear story"]', '{"fun_facts": ["Publishers receive 100+ pitches monthly", "2-minute elevator pitch opens doors", "Market comparison is essential"], "career_connections": ["Game Producer", "Business Developer", "Pitch Consultant"], "company_examples": ["Devolver Digital", "Team17", "Raw Fury"]}', 'teen'),
  
  ('Discord Community', 'Build a Discord server for a new indie game that creates an engaged community before launch.', 'Design your Discord server structure: Channels, roles, rules, and engagement activities.', 'thought', 'build', gaming_id, 'easy', 4, 25, '["Community Building", "Discord Setup", "Engagement"]', '["Creates channel structure", "Designs engagement activities", "Sets clear rules"]', '{"fun_facts": ["Games with strong Discord communities sell 40% more", "Welcome bots improve retention 25%", "Too many channels kills engagement"], "career_connections": ["Community Manager", "Discord Moderator", "Player Engagement Lead"], "company_examples": ["Among Us", "Valorant", "Genshin Impact"]}', 'teen'),
  
  ('Game Trailer Script', 'Write a 60-second trailer script for an indie game that hooks viewers in the first 5 seconds.', 'Write your trailer script: What do viewers see and hear in each 15-second segment?', 'thought', 'build', gaming_id, 'medium', 4, 30, '["Video Scripting", "Marketing", "Storytelling"]', '["Creates compelling hook", "Shows gameplay", "Ends with call to action"]', '{"fun_facts": ["85% of viewers decide in first 5 seconds", "Show don''t tell works best for games", "Music choice affects perception 50%"], "career_connections": ["Game Marketing Manager", "Video Producer", "Creative Director"], "company_examples": ["PlayStation", "Nintendo", "CD Projekt"]}', 'teen'),
  
  ('Streaming Setup Guide', 'Create a beginner-friendly guide to start streaming with under $500 budget.', 'List the essential equipment and setup steps for someone starting their streaming journey.', 'decision', 'build', gaming_id, 'easy', 4, 25, '["Streaming Tech", "Budget Planning", "Tutorial Creation"]', '["Lists essential equipment", "Stays within budget", "Provides clear steps"]', '{"fun_facts": ["You can start streaming with a phone", "Audio quality matters more than video", "OBS is free and professional-grade"], "career_connections": ["Content Creator", "Streaming Coach", "Tech Reviewer"], "company_examples": ["Elgato", "Blue", "Logitech"]}', 'teen');

  -- EXPLORE pillar (7 challenges)
  INSERT INTO challenges (title, scenario, question, category, pillar, industry_track_id, difficulty_level, estimated_minutes, xp_reward, skills_developed, success_criteria, real_world_context, age_range) VALUES
  ('Nintendo''s Strategy', 'Nintendo consistently succeeds with "inferior" hardware by focusing on unique experiences and beloved IP.', 'What makes Nintendo''s business strategy work when they don''t compete on specs or power?', 'thought', 'explore', gaming_id, 'medium', 4, 30, '["Business Strategy", "Competitive Analysis", "Brand"]', '["Explains strategy", "Identifies success factors", "Shows industry understanding"]', '{"fun_facts": ["Switch outsold PS4 despite weaker hardware", "Mario is more recognized than Mickey Mouse", "Nintendo focuses on fun over graphics"], "career_connections": ["Game Industry Analyst", "Brand Strategist", "Business Developer"], "company_examples": ["Nintendo", "Sony", "Microsoft"]}', 'teen'),
  
  ('China Gaming Rules', 'China limits minors to 3 hours of gaming per week. This has huge implications for the global gaming industry.', 'What are the effects of China''s gaming restrictions, and should other countries do similar?', 'thought', 'explore', gaming_id, 'hard', 5, 35, '["Policy Analysis", "Global Markets", "Ethics"]', '["Analyzes effects", "Forms opinion", "Shows global perspective"]', '{"fun_facts": ["China is 25% of global gaming market", "Tencent stock dropped 20% after rules", "Kids use parents'' IDs to bypass limits"], "career_connections": ["Policy Analyst", "Game Industry Consultant", "International Business"], "company_examples": ["Tencent", "NetEase", "miHoYo"]}', 'teen'),
  
  ('VR Future', 'VR has been "the next big thing" for decades. It keeps improving but mass adoption remains elusive.', 'Will VR ever become mainstream gaming, or will it remain niche? What would need to change?', 'thought', 'explore', gaming_id, 'hard', 5, 35, '["Technology Forecasting", "Adoption Barriers", "Industry Analysis"]', '["Predicts trajectory", "Identifies barriers", "Shows balanced analysis"]', '{"fun_facts": ["Quest 2 sold 20M units", "VR causes motion sickness in 40% of users", "Wireless VR was the breakthrough"], "career_connections": ["VR Developer", "Hardware Analyst", "Future Strategist"], "company_examples": ["Meta", "Sony PSVR", "Valve"]}', 'teen'),
  
  ('Games as Art', 'The "are games art?" debate has raged for decades. Games are now in museums, but not all agree.', 'Are video games art? Make an argument for your position using specific game examples.', 'thought', 'explore', gaming_id, 'medium', 4, 30, '["Critical Thinking", "Media Analysis", "Argumentation"]', '["Takes clear position", "Uses examples", "Shows thoughtful analysis"]', '{"fun_facts": ["MoMA has 14 games in its collection", "Journey won Grammy for best game music", "Some argue games are the ultimate art form"], "career_connections": ["Game Critic", "Art Director", "Game Studies Professor"], "company_examples": ["thatgamecompany", "Playdead", "Team ICO"]}', 'teen'),
  
  ('Roblox Economy', 'Roblox has created millions of young game developers who earn real money creating games and items.', 'Is Roblox empowering young creators or exploiting their labor? Analyze both perspectives.', 'thought', 'explore', gaming_id, 'hard', 5, 35, '["Platform Economics", "Ethics", "Creator Economy"]', '["Analyzes both sides", "Uses evidence", "Forms nuanced view"]', '{"fun_facts": ["Roblox developers earned $540M in 2022", "Roblox takes 75% of Robux purchases", "Average developer earns under $100"], "career_connections": ["Platform Economist", "Creator Rights Advocate", "Game Platform PM"], "company_examples": ["Roblox", "Epic Games", "Unity"]}', 'teen'),
  
  ('Gaming & Career Skills', 'Gamers develop skills like strategic thinking, teamwork, and rapid decision-making. But resumes rarely mention gaming.', 'What transferable skills do gamers develop, and how should they present them to employers?', 'thought', 'explore', gaming_id, 'easy', 3, 25, '["Career Development", "Skill Translation", "Self-Awareness"]', '["Identifies transferable skills", "Shows how to present them", "Makes career connection"]', '{"fun_facts": ["Military uses games for strategy training", "Surgeons who game make 37% fewer errors", "Esports pros have reaction times of 150ms"], "career_connections": ["Career Coach", "HR Specialist", "Skills Researcher"], "company_examples": ["LinkedIn", "EEDAR", "SuperData"]}', 'teen'),
  
  ('Indie vs AAA', 'Indie games like Stardew Valley and Among Us compete with $100M AAA games and sometimes win.', 'How do indie games compete with AAA titles that have 100x the budget?', 'thought', 'explore', gaming_id, 'medium', 4, 30, '["Competitive Strategy", "Game Business", "Innovation"]', '["Identifies indie advantages", "Shows industry understanding", "Explains success factors"]', '{"fun_facts": ["Stardew Valley was made by one person", "Among Us took 2 years to become viral", "Indie games have higher ROI on average"], "career_connections": ["Indie Developer", "Game Publisher", "Investment Analyst"], "company_examples": ["ConcernedApe", "InnerSloth", "Supergiant Games"]}', 'teen');

END $$;